# Generated by Django 5.1.1 on 2024-10-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='charge',
            field=models.IntegerField(default=0),
        ),
    ]
